import logging
from pathlib import Path
from typing import Literal

from . import catalog

log = logging.getLogger("agentic-hub")

HOME = Path.home()

Mode = Literal["symlink", "codex"]
Status = Literal["linked", "stale", "missing", "conflict"]

# agent -> (target dir, mode)
AGENTS: dict[str, tuple[Path, Mode]] = {
    "claude": (HOME / ".claude/skills", "symlink"),
    "pi": (HOME / ".pi/agent/skills", "symlink"),
    "opencode": (HOME / ".config/opencode/skill", "symlink"),
    "codex": (HOME / ".codex/prompts", "codex"),
}

CODEX_MARKER = "<!-- agentic-hub: generated, do not edit -->"


def target_path(agent: str, name: str) -> Path:
    """Where a skill would live for this agent (symlink path or generated file)."""
    dir_, mode = AGENTS[agent]
    return dir_ / (f"{name}.md" if mode == "codex" else name)


def is_our_codex_file(path: Path) -> bool:
    """Check the marker on the first line to see if we generated this file."""
    try:
        first_line = path.read_text().splitlines()[0]
    except (OSError, IndexError):
        return False
    return first_line.strip() == CODEX_MARKER


def _is_ours_symlink(tp: Path, sp: Path) -> bool:
    try:
        return tp.resolve() == sp.resolve()
    except OSError:
        return False


def status(agent: str, name: str) -> Status:
    """Report whether a skill is linked, stale, missing, or conflicting for an agent."""
    dir_, mode = AGENTS[agent]
    tp = target_path(agent, name)
    if mode == "symlink":
        if tp.is_symlink():
            return "linked" if _is_ours_symlink(tp, catalog.SKILLS_DIR / name) else "stale"
        return "conflict" if tp.exists() else "missing"
    if tp.exists():
        return "linked" if is_our_codex_file(tp) else "conflict"
    return "missing"


def install_one(agent: str, name: str) -> bool:
    """Install (symlink or generate) one skill for one agent; False if skipped."""
    dir_, mode = AGENTS[agent]
    sp = catalog.SKILLS_DIR / name
    tp = target_path(agent, name)
    dir_.mkdir(parents=True, exist_ok=True)
    if mode == "symlink":
        if tp.exists() and not tp.is_symlink():
            log.warning("skip %s/%s: %s is a real file/dir, not ours", agent, name, tp)
            return False
        if status(agent, name) == "linked":
            log.debug("ok %s/%s: already linked", agent, name)
            return True
        relinked = tp.is_symlink()
        if tp.is_symlink() or tp.exists():
            tp.unlink()
        tp.symlink_to(sp, target_is_directory=True)
        log.info(
            "%s %s/%s -> %s", "relinked" if relinked else "linked", agent, name, tp
        )
        return True
    if tp.exists() and not is_our_codex_file(tp):
        log.warning(
            "skip %s/%s: %s exists and wasn't generated by agentic-hub", agent, name, tp
        )
        return False
    fm, body = catalog.parse_frontmatter((sp / "SKILL.md").read_text())
    tp.write_text(f"{CODEX_MARKER}\n{fm.get('description', '')}\n\n{body}")
    log.info("generated %s/%s -> %s", agent, name, tp)
    return True


def remove_one(agent: str, name: str) -> bool:
    """Remove a skill we installed for an agent; False if there's nothing to remove."""
    dir_, mode = AGENTS[agent]
    tp = target_path(agent, name)
    if mode == "symlink":
        if tp.is_symlink() and _is_ours_symlink(tp, catalog.SKILLS_DIR / name):
            tp.unlink()
            log.info("unlinked %s/%s (%s)", agent, name, tp)
            return True
    elif tp.is_file() and is_our_codex_file(tp):
        tp.unlink()
        log.info("deleted %s/%s (%s)", agent, name, tp)
        return True
    log.debug(
        "nothing to remove for %s/%s: %s",
        agent,
        name,
        "not ours" if tp.exists() else "not installed",
    )
    return False
